project:
  type: website
  output-dir: docs
website:
  title: "Drug Target and Biomarker Discovery Laboratory"
  favicon: favicon.png
  navbar:
    background: "#f6f8fa"
    foreground: "#111827"
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: join.qmd
        text: Join Us
      - href: news.qmd
        text: News

  page-footer:
    left: "© Drug Target and Biomarker Discovery Laboratory"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full