project:
  type: website
  output-dir: docs
website:
  title: "Drug Target and Biomarker Discovery Laboratory"
  navbar:
    background: "#ffffff"
    foreground: "#111827"
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: join.qmd
        text: Join Us

  page-footer:
    left: "© Drug Target and Biomarker Discovery Laboratory"
    right: "Built with Quarto"

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: false
    page-layout: article
