project:
  type: website
  output-dir: docs

website:
  title: "Drug Target and Biomarker Discovery Laboratory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
      - href: news.qmd
        text: News
      - href: contact.qmd
        text: About

  page-footer:
    center: "© Drug Target and Biomarker Discovery Laboratory. All rights reserved."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false