# People

## Principal Investigator

:::: profile-box
::: {}
### Jiyoun Lee

Professor\
School of Biopharmaceutical and Medical Sciences\
Sungshin University

[Google Scholar](https://scholar.google.co.kr/citations?user=UC9dtGIAAAAJ&hl=en)\
[ORCID](http://orcid.org/0000-0003-3819-5889)\
[CV](https://chembiolab.weebly.com/uploads/5/8/1/0/58104541/jlee_cv_2023.pdf)\
Email: jlee at sungshin.ac.kr\
Phone: +82-2-920-7281
:::
::::

## Education

- 2006: Ph.D. in Bioinorganic Chemistry, Northwestern University\
  Advisor: Prof. Thomas J. Meade
- 2000: M.S. in Medicinal Chemistry, Seoul National University\
  Advisor: Prof. Jeewoo Lee
- 1998: B.S. in Pharmacy, Seoul National University

## Experience

- 2023–Present: Professor, School of Biopharmaceutical and Medical Sciences, Sungshin University
- 2021–2022: Associate Professor, School of Biopharmaceutical and Medical Sciences, Sungshin University
- 2018–2022: Associate Professor, Department of Global Medical Science, Sungshin University
- 2012–2017: Assistant Professor, Department of Global Medical Science, Sungshin University
- 2010–2012: Senior Research Scientist, Korea Institute of Science and Technology
- 2008–2010: Postdoctoral Research Associate, Stanford University School of Medicine\
  Advisor: Prof. Matthew Bogyo
- 2006–2007: Postdoctoral Research Associate, University of California, Berkeley\
  Advisor: Prof. Christopher J. Chang

## Current Members

:::::::: member-grid
::: member-card
**김은지**\
Ph.D. student
:::

::: member-card
**류주희**\
M.S. student
:::

::: member-card
**김혜민**\
M.S. student
:::

::: member-card
**박주희**\
Combined B.S./M.S. student
:::

::: member-card
**신보영**\
Undergraduate researcher
:::
::::::::

## Alumni

- 나여경, M.S. 2015–2017, 단디큐어
- 홍종아, M.S. 2016–2018, 식약처
- 이지유, M.S. 2020–2022, 피코엔텍
- 박은채, M.S. 2021–2023, 이람화학
- 한수정, M.S. 2023–2025, 한국건설생활환경시험연구원
- 이유나, M.S. 2024–2026, 대구경북첨단의료산업진흥재단 신약개발센터

## Honorary Members

**2024**

- 전혜빈, M.S. student
- 박수윤, Undergraduate researcher (화학에너지융합학부)
- 정지현, Undergraduate researcher (화학에너지융합학부 4학년)

**2022**

- 최나은, Researcher, 펩스젠

**2021**

- 송유정, Undergraduate researcher (바이오생명공학과 졸업)
- 이설아, Undergraduate researcher (글로벌의과학과 졸업)

**2020**

- 이주희, Undergraduate researcher (글로벌의과학과 졸업)

**2019**

- 어진이, Researcher/Undergraduate researcher (2018), 강원대 의전원

**2018**

- 송다솜, Researcher, 광주과기원 화학과 박사과정
- 박영훈, Graduate student

**2017**

- 박은비, Undergraduate researcher, 소위임관
- 정혜지, Undergraduate researcher, DGIST 뇌인지과학전공 석사과정
- 최다은, Undergraduate researcher
- 김민지, Undergraduate researcher

**2016**

- 김민지, Undergraduate researcher
- 정유진, Undergraduate researcher, AUA

**2015**

- 정수정, Undergraduate researcher